#!/bin/bash

echo "🚀 GitHub Deployment - Quick Commands"
echo "======================================"
echo ""
echo "✅ Git is already initialized and committed!"
echo ""
echo "📋 STEP 1: Create GitHub Repository"
echo "Go to: https://github.com/new"
echo "  - Name: synergy-attendance-tracker"
echo "  - Visibility: Private"
echo "  - DON'T check 'Initialize with README'"
echo "  - Click 'Create repository'"
echo ""
echo "📋 STEP 2: Run These Commands"
echo ""
echo "Replace YOUR_USERNAME with your actual GitHub username:"
echo ""
echo "cd \"/Users/tasneemzaman/Desktop/Attendance Tracker Synergy\""
echo "git remote add origin https://github.com/YOUR_USERNAME/synergy-attendance-tracker.git"
echo "git push -u origin main"
echo ""
echo "======================================"
echo ""
echo "After pushing to GitHub:"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Create 'New Web Service'"
echo "4. Connect your repository"
echo "5. Use these settings:"
echo "   - Build Command: npm install"
echo "   - Start Command: node server.js"
echo "   - Plan: FREE"
echo ""
echo "Full guide: See DEPLOYMENT_INSTRUCTIONS.md"
echo ""
